kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc-{{ .Values.cnf }}
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.fsid }}
  directoryPerms: "700"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/dynamic_provisioning" # optional
